### ISSUE TITLE
Publishing to Ruby gems.

### ISSUE THREAD

**Issue by j-mcnally** [InkedFur/clover-ruby#1]
Any idea when you might be publishing to ruby gems.

We're going to be developing and depending on this i believe, so in the mean time we've forked to make sure we can anchor for releases and we'll just pull from the upstream.

Having a formal release will make this easier and we're less likely to need our fork.

**Comment by colinxchristmas** [comment]
@j-mcnally Did you end up finding a work-around? I'm having issues and I'm too new to this to figure out where it is.

Initialization keeps failing due to `#<NoMethodError: undefined method 'configure' for Clover:Module>`

I wonder if forking it might just do the fix...

**Comment by j-mcnally** [comment]
We just rolled our own entire integration. Sorry.
